CREATE TABLE IF NOT EXISTS PUBLIC.FILM (
	ID BIGINT AUTO_INCREMENT,
	NAME CHARACTER VARYING(255) NOT NULL,
	DESCRIPTION CHARACTER VARYING(255) NOT NULL,
	RELEASE_DATE DATE NOT NULL,
	DURATION INTEGER NOT NULL,
	MPA CHARACTER VARYING(4) NOT NULL,
	CONSTRAINT FILM_PK PRIMARY KEY (ID)
);